In [1]:
!pip install numpy

In [2]:
!pip install numpy --upgrade

  Found existing installation: numpy 1.16.2
    Uninstalling numpy-1.16.2:
      Successfully uninstalled numpy-1.16.2


tables 3.5.1 requires mock>=2.0, which is not installed.


In [3]:
import numpy as np

In [4]:
array_one = np.array([1,2,3,4])
array_one

array([1, 2, 3, 4])

In [5]:
type(array_one)

numpy.ndarray

In [6]:
numbers = [7,8,9,10]
array_two = np.array(numbers)
array_two

array([ 7,  8,  9, 10])

In [8]:
type(numbers)

list

In [9]:
array_of_zeros = np.zeros((3,4))

In [10]:
array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
array_of_ones = np.ones((4,5))
array_of_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
array_of_ones_int = np.ones((3,4), dtype=np.int16)
array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)