In [1]:
import numpy as np

In [7]:
ages = np.array({12,15,18,20})

In [8]:
ages.min()

{12, 15, 18, 20}

In [9]:
ages.max()

{12, 15, 18, 20}

In [10]:
ages.sum()

{12, 15, 18, 20}

In [13]:
numbers = np.arange(12).reshape(3,4)
numbers

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
numbers.sum(axis=0)

array([12, 15, 18, 21])

In [15]:
numbers.sum(axis=1)

array([ 6, 22, 38])