In [18]:
import numpy as np

In [6]:
array_eye = np.eye(4)
eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
array_eye1 = np.eye(3)
array_eye1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
!pip install numpy

In [17]:
!pip install numpy --upgrade

Requirement already up-to-date: numpy in c:\users\karth\anaconda3\lib\site-packages (1.19.1)


In [19]:
array_of_numbers = np.arange(6)
array_of_numbers

array([0, 1, 2, 3, 4, 5])

In [20]:
array_of_evens = np.arange(2,30,2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [21]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [22]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [23]:
x.shape

(6,)

In [24]:
y = np.arange(6).reshape(2,3)
y

array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
y.shape

(2, 3)

In [26]:
y = np.arange(6).reshape(3,2)
y

array([[0, 1],
       [2, 3],
       [4, 5]])

In [27]:
y.shape

(3, 2)

In [28]:
z = np.arange(12).reshape(2,3,2)
z

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [29]:
z.shape

(2, 3, 2)

In [30]:
z = np.arange(12).reshape(6,2)
z

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [31]:
z.shape

(6, 2)